name: Create Tag on PR Merge

on:
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get PR Info from environment
        run: |
          # Read the PR info that was stored in the environment
          PR_TITLE="${{ github.event.workflow_run.head_commit.message }}"
          PR_BODY="${{ github.event.workflow_run.head_commit.body || 'No description provided.' }}"

          # Generate a valid tag name from PR title (replace spaces with underscores)
          TAG_NAME="${PR_TITLE// /_}"
          echo "Tag Name: $TAG_NAME"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag_and_release.outputs.tag_name }}
          release_name: "${{ steps.create_tag_and_release.outputs.tag_name }}"
          body: "${{ steps.create_tag_and_release.outputs.PR_BODY }}"
          draft: false
          prerelease: false
