name: Create Tag on PR Merge

on:
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get the PR Info from the previous workflow
        run: |
          # Fetch the information that was passed via the GITHUB_ENV in the PR Workflow
          PR_TITLE="${{ github.event.workflow_run.head_commit.message }}"
          PR_BODY="${{ github.event.workflow_run.head_commit.body || 'No description provided.' }}"

          # Create a tag based on the PR title
          TAG_NAME="${PR_TITLE// /_}"  # Replace spaces with underscores for the tag
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

          echo "Tag created: $TAG_NAME"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "${{ env.TAG_NAME }}"
          body: |
            ${{ github.event.workflow_run.head_commit.body || 'No description provided.' }}
          draft: false
          prerelease: false
