name: Create Tag on PR Merge

on:
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Read the PR info from the environment
        run: |
          # Simulate reading PR title and body from environment variables set in the previous job
          PR_TITLE="${{ github.event.workflow_run.head_commit.message }}"
          PR_BODY="${{ github.event.workflow_run.head_commit.body || 'No description provided.' }}"

          # Generate a valid tag name from PR title (replace spaces with underscores)
          TAG_NAME="${PR_TITLE// /_}"
          echo "Tag Name: $TAG_NAME"
          echo "PR_BODY: $PR_BODY"

          # Store TAG_NAME and PR_BODY into environment to use in later steps
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "PR_BODY=${PR_BODY}" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag "${{ env.TAG_NAME }}"
          git push origin "${{ env.TAG_NAME }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "${{ env.TAG_NAME }}"
          body: "${{ env.PR_BODY }}"
          draft: false
          prerelease: false
