name: Create Tag on PR Merge or Manual Dispatch

on:
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name (will be used if manually triggered)"
        required: true
      release_body:
        description: "Release description (will be used if manually triggered)"
        required: true

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch PR Info or Use Manual Inputs
        id: pr_info
        if: github.event_name == 'workflow_dispatch'
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          PR_BODY="${{ github.event.inputs.release_body }}"

          printf "TAG_NAME=%s\n" "$TAG_NAME" >> $GITHUB_ENV
          printf "PR_BODY=%s\n" "$PR_BODY" >> $GITHUB_ENV

      - name: Fetch PR Info for Workflow Run
        if: github.event_name != 'workflow_dispatch'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: prs } = await octokit.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 10
            });

            const mergedPr = prs.find(pr => pr.merged_at);
            if (!mergedPr) {
              throw new Error("No merged PR found");
            }

            core.setOutput('pr_number', mergedPr.number);
            core.setOutput('pr_title', mergedPr.title);
            core.setOutput('pr_body', mergedPr.body || "No description provided");

      - name: Set PR Info from API
        if: github.event_name != 'workflow_dispatch'
        run: |
          printf "TAG_NAME=%s\n" "${{ steps.fetch_pr_info.outputs.pr_title }}" >> $GITHUB_ENV
          printf "PR_BODY=%s\n" "${{ steps.fetch_pr_info.outputs.pr_body }}" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          # Replace spaces with underscores in the tag name
          TAG_NAME="${{ env.TAG_NAME }}"
          TAG_NAME=$(echo "$TAG_NAME" | sed 's/ /_/g')

          # Create and push the tag
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

          echo "Tag Name: $TAG_NAME"
          echo "PR Body: ${{ env.PR_BODY }}"

          # Store the tag name to use in the next step
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create spectrocoin.zip
        run: |
          mkdir spectrocoin-accepting-bitcoin  # Create the folder inside the working directory
          # Copy only the necessary files and exclude the folder and unwanted files
          find . -maxdepth 1 ! -name 'spectrocoin-accepting-bitcoin' ! -name '.' ! -name '.git' ! -name '.github' ! -name 'README.txt' ! -name 'README.md' ! -name 'changelog.md' ! -name '.gitignore' -exec cp -r {} spectrocoin-accepting-bitcoin/ \;
          zip -r spectrocoin.zip spectrocoin-accepting-bitcoin  # Zip the folder
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "${{ env.TAG_NAME }}"
          body: "${{ env.PR_BODY }}"
          draft: false
          prerelease: false

      - name: Upload spectrocoin.zip as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: spectrocoin.zip
          asset_name: spectrocoin.zip
          asset_content_type: application/zip
